// packages/ion/src/Button.tsx
"use client";
// ion/Button: Generated with Ion on 2/26/2024, 3:24:45 PM
import { cva } from "class-variance-authority";
import clsx from "clsx";
import * as React from "react";
import { twMerge } from "tailwind-merge";

export const buttonVariants = cva(
  [
    "flex",
    "items-center",
    "justify-center",
    "rounded-radius",
    "disabled:pointer-events-none",
    "whitespace-nowrap",
    "border",
    "h-fit",
  ],
  {
    variants: {
      emphasis: {
        gradient: "disabled:bg-soft disabled:text-soft-foreground border-none",
        link: "disabled:text-soft-foreground border-none",
        high: "disabled:bg-soft disabled:text-soft-foreground border-transparent",
        medium:
          "disabled:border-weak-stroke disabled:text-weak-foreground focus:bg-white focus:bg-opacity-0",
        low: "focus:bg-white focus:bg-opacity-0 disabled:text-weak-foreground border-transparent",
      },
      color: {
        primary: "focus:primary-focus",
        secondary: "focus:secondary-focus",
        danger: "focus:danger-focus",
      },
      size: {
        sm: "gap-x-1 px-2 py-1 text-sm",
        md: "gap-x-1 px-3 py-2 text-sm",
        lg: "gap-x-2 px-4 py-3 text-base",
        "icon-sm": "h-7 w-7",
        "icon-md": "h-8 w-8",
        "icon-lg": "h-10 w-10",
      },
    },
    compoundVariants: [
      ...(["primary", "secondary", "danger"] as const).flatMap((color) =>
        [
          {
            emphasis: ["link" as const],
            color: [color],
            className: [
              `hover:text-${color}-dark`,
              `active:text-${color}-darker`,
              `text-${color}`,
              "p-0 pr-1",
            ],
          },

          {
            emphasis: ["low" as const],
            color: [color],
            className: [
              `hover:bg-${color}-lightest`,
              `active:bg-${color}-lighter`,
              `text-${color}`,
            ],
          },
          {
            emphasis: ["medium" as const],
            color: [color],
            className: [
              `border-${color}`,
              `hover:bg-${color}-lightest`,
              `hover:border-${color}-dark`,
              `active:bg-${color}-lighter`,
              `active:border-${color}-dark`,
              `text-${color}`,
              `hover:text-${color}-dark`,
              `active:text-${color}-darker`,
            ],
          },
          {
            emphasis: ["high" as const],
            color: [color],
            className: [
              `hover:bg-${color}-dark`,
              `hover:border-${color}-dark`,
              `active:bg-${color}-darker`,
              `active:border-${color}-dark`,
              `text-${color}-foreground`,
              `bg-${color}`,
            ],
          },
          {
            emphasis: ["gradient" as const],
            color: [color],
            className: [
              `bg-blend-overlay bg-gradient-to-r from-white/40 to-white/0 bg-${color}`,
              `hover:bg-${color}-dark`,
              `active:bg-${color}-darker`,
              `dark:hover:bg-${color}-light`,
              `dark:active:bg-${color}-lighter`,
              `text-${color}-foreground`,
            ],
          },
        ].flat()
      ),
    ],
  }
);

export type ButtonSizes =
  | "sm"
  | "md"
  | "lg"
  | "icon-sm"
  | "icon-md"
  | "icon-lg";

export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  children?: React.ReactNode | React.ReactNode[];
  iconLeading?: React.ReactNode;
  iconTrailing?: React.ReactNode;
  color?: "primary" | "secondary" | "danger";
  emphasis?: "high" | "medium" | "low" | "gradient" | "link";
  size?: "sm" | "md" | "lg";
};

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      className,
      children,
      iconTrailing,
      iconLeading,
      color = "primary",
      emphasis = "high",
      size = "md",
      ...props
    },
    ref
  ) => {
    return (
      <button
        className={twMerge(
          clsx(
            buttonVariants({
              color,
              emphasis,
              size:
                (iconLeading || iconTrailing) && !children
                  ? `icon-${size}`
                  : size,
            }),
            "transition-shadows transition-colors",
            className
          )
        )}
        ref={ref}
        {...props}
      >
        {iconLeading}
        {children}
        {iconTrailing}
      </button>
    );
  }
);
Button.displayName = "Button";

// apps/web/src/components/solid/ui/button.tsx
import type { Component, ComponentProps } from "solid-js"
import { splitProps } from "solid-js"
 
import type { VariantProps } from "class-variance-authority"
import { cva } from "class-variance-authority"
 
import { cn } from "@/lib/utils"
 
const buttonVariants = cva(
  "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline: "border border-input hover:bg-accent hover:text-accent-foreground",
        secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline"
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
        icon: "size-10"
      }
    },
    defaultVariants: {
      variant: "default",
      size: "default"
    }
  }
)
 
export interface ButtonProps
  extends ComponentProps<"button">,
    VariantProps<typeof buttonVariants> {}
 
const Button: Component<ButtonProps> = (props) => {
  const [, rest] = splitProps(props, ["variant", "size", "class"])
  return (
    <button
      class={cn(buttonVariants({ variant: props.variant, size: props.size }), props.class)}
      {...rest}
    />
  )
}
 
export { Button, buttonVariants }
