// apps/web/src/components/react/search-bar.tsx
import { GoSearch } from 'react-icons/go';
import { LuSettings2 } from 'react-icons/lu';
import { Button } from '@repo/ion/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@repo/shadcn/dialog';
import { cn } from '@/lib/utils';
import { useReducer } from 'react';

type FormState = {
  search: string;
  entityType: string[];
  entitySubtype: string[];
  entityStatus: string[];
};

type OverwriteAction = {
  type: 'OVERWRITE_STATE';
  payload: FormState;
};
type Action = {
  type:
    | 'UPDATE_SEARCH'
    | 'TOGGLE_ENTITY_TYPE'
    | 'TOGGLE_ENTITY_SUBTYPE'
    | 'TOGGLE_ENTITY_STATUS';
  payload: string;
};

function toggleArray(arr: string[], value: string) {
  if (arr.includes(value)) {
    return arr.filter((type) => type !== value);
  }
  return [...arr, value];
}
function reducer(state: FormState, action: Action | OverwriteAction) {
  switch (action.type) {
    case 'UPDATE_SEARCH':
      return { ...state, search: action.payload };
    case 'TOGGLE_ENTITY_TYPE':
      return {
        ...state,
        entityType: toggleArray(state.entityType, action.payload),
      };
    case 'TOGGLE_ENTITY_STATUS':
      return {
        ...state,
        entityStatus: toggleArray(state.entityStatus, action.payload),
      };
    case 'TOGGLE_ENTITY_SUBTYPE':
      return {
        ...state,
        entitySubtype: toggleArray(state.entitySubtype, action.payload),
      };
    case 'OVERWRITE_STATE':
      return {
        ...action.payload,
        entityStatus: [...action.payload.entityStatus],
        entityType: [...action.payload.entityType],
        entitySubtype: [...action.payload.entitySubtype],
      };
    default:
      return state;
  }
}

function getDefaultState() {
  return {
    search: '',
    entityType: [],
    entitySubtype: [],
    entityStatus: [],
  };
}

export function FilterButton({
  children,
  isActive,
  onClick,
}: {
  children: React.ReactNode;
  isActive: boolean;
  onClick: () => void;
}) {
  return (
    <Button
      className={cn(
        'rounded-[4px] px-6 active:bg-inherit',
        isActive ?
          'bg-primary-lighter focus:bg-primary-lighter'
        : 'focus:bg-white',
      )}
      onClick={onClick}
      emphasis="medium"
    >
      {children}
    </Button>
  );
}
const mediaTypes = ['anime', 'manga', 'character'];
const animeSubtypes = ['tv', 'movie', 'ova', 'special', 'ona', 'music'];
const mangaSubtypes = [
  'manga',
  'novel',
  'lightnovel',
  'oneshot',
  'doujin',
  'manhwa',
  'manhua',
];
const animeStatuses = ['airing', 'complete', 'upcoming'];
const mangaStatuses = [
  'publishing',
  'complete',
  'hiatus',
  'discontinued',
  'upcoming',
];
export function SearchBar() {
  const [state, dispatch] = useReducer(reducer, getDefaultState());
  const [modalState, modalDispatch] = useReducer(reducer, getDefaultState());
  return (
    <div className="h-12 bg-gray-100 border-0 outline-none p-3 rounded-sm flex items-center mt-4 gap-x-2">
      <GoSearch size={22} className="text-neutral-500" />
      <input
        type="search"
        placeholder="Jujutsu kaisen, Naruto, Tokyo Revengers..."
        className="border-0 outline-none bg-inherit text-neutral-500 w-full"
        value={state.search}
        onChange={(e) =>
          dispatch({ type: 'UPDATE_SEARCH', payload: e.target.value })
        }
      />
      <Dialog
        onOpenChange={(open) => {
          if (!open) {
            modalDispatch({ type: 'OVERWRITE_STATE', payload: state });
          }
        }}
      >
        <DialogTrigger asChild>
          <Button className="bg-white active:bg-black active:text-gray-100 focus:bg-white focus:text-black hover:bg-black border-0 hover:text-gray-100 rounded-sm text-sm h-[34px] gap-x-1 ">
            <LuSettings2 size={17} />
            Filters
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[425px] rounded-sm text-black">
          <DialogHeader>
            <DialogTitle className="text-black font-inter text-left">
              Filters
            </DialogTitle>
            <DialogDescription className="text-left text-gray-500"></DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div>
              <h4 className="text-gray-500 text-inter">Media</h4>
              <div className="grid grid-cols-[repeat(auto-fill,minmax(100px,1fr))] mt-3 gap-2 gap-x-4 max-w-[375px]">
                {mediaTypes.map((type) => (
                  <FilterButton
                    isActive={modalState.entityType.includes(type)}
                    onClick={() =>
                      modalDispatch({
                        type: 'TOGGLE_ENTITY_TYPE',
                        payload: type,
                      })
                    }
                  >
                    {type}
                  </FilterButton>
                ))}
              </div>
            </div>
            <div>
              <h4 className="text-gray-500 text-inter">Select media type</h4>
              <div className="grid grid-cols-[repeat(auto-fill,minmax(100px,1fr))] mt-3 gap-2 gap-x-4 max-w-[375px]">
                {[...animeSubtypes, ...mangaSubtypes].map((type) => (
                  <FilterButton
                    isActive={modalState.entitySubtype.includes(type)}
                    onClick={() =>
                      modalDispatch({
                        type: 'TOGGLE_ENTITY_SUBTYPE',
                        payload: type,
                      })
                    }
                  >
                    {type}
                  </FilterButton>
                ))}
              </div>
            </div>
            <div>
              <h4 className="text-gray-500 text-inter">Select media status</h4>
              <div className="grid grid-cols-[repeat(auto-fill,minmax(100px,1fr))] mt-3 gap-2 gap-x-4 max-w-[375px]">
                {[...new Set([...animeStatuses, ...mangaStatuses])].map(
                  (type) => (
                    <FilterButton
                      isActive={state.entityStatus.includes(type)}
                      onClick={() =>
                        dispatch({
                          type: 'TOGGLE_ENTITY_STATUS',
                          payload: type,
                        })
                      }
                    >
                      {type}
                    </FilterButton>
                  ),
                )}
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button
              className="rounded-sm text-white"
              color="primary"
              type="button"
              onClick={() =>
                dispatch({ type: 'OVERWRITE_STATE', payload: modalState })
              }
            >
              Save changes
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      <Button className="bg-black rounded-sm h-[34px] hover:bg-black border-0">
        <GoSearch size={17} className="text-white font-bold" />
      </Button>
    </div>
  );
}

// src/components/solid/search-bar.tsx
import { Show, createSignal } from 'solid-js';
import { SelectSearchType } from "./select-search-type"
import { AiOutlineSearch } from 'solid-icons/ai'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from './ui/select';
import clsx from 'clsx';

export function SearchBar() {
  const [searchType, setSearchType] = createSignal('anime');
  return (
    <form action="/search" method="get">
      <div class="flex relative">
        <Select
          name="searchType"
          value={searchType()}
          onChange={setSearchType}
          placeholder="anime"
          options={['anime', 'manga', 'character']}
          itemComponent={(props) => (
            <SelectItem item={props.item}>{props.item.rawValue}</SelectItem>
          )}
        >
          <SelectTrigger
            name="searchType"
            class={clsx(
              'w-32 rounded-l-md flex-none text-gray-500 h-10 rounded-r-none'
            )}
          >
            <SelectValue<string>>{(state) => state.selectedOption()}</SelectValue>
          </SelectTrigger>
          <SelectContent class={clsx("w-40 bg-white h-[7.5rem]")} />
        </Select>
        <input
          name="q"
          class="flex border border-input bg-transparent px-3 py-2 file:border-0 file:bg-transparent file:text-sm placeholder:text-[14px] file:font-medium focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 placeholder:text-gray-500 w-full min-w-[100px] max-w-[288px] h-10 text-[14px] border-l-0 text-gray-500"
          placeholder="Search..."
        />
        <button
          class="inline-flex overflow-hidden relative items-center justify-center transitions-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none text-sm font-montserrat font-semibold text-white bg-neutral-800 hover:bg-neutral-900 rounded-none h-10 w-12 rounded-r-md p-0 flex-none"
        >
          <AiOutlineSearch size={18} />
        </button>
      </div>
      <p class="text-neutral-500 font-medium text-sm my-2">Filters:</p>
      <div class="flex gap-x-10">
        <Show when={searchType() === 'anime'}>
          <label class="text-neutral-500 text-sm">
            <p class="mb-2 font-medium">Type:</p>
            <SelectSearchType
              name="type"
              options={['all', 'tv', 'movie', 'ova', 'special', 'ona', 'music']}
            />
          </label>
          <label class="text-neutral-500 text-sm">
            <p class="mb-2 font-medium">Status:</p>
            <SelectSearchType
              name="status"
              options={['all', 'airing', 'complete', 'upcoming']}
            />
          </label>
        </Show>
        <Show when={searchType() === 'manga'}>
          <label class="text-neutral-500 text-sm">
            <p class="mb-2 font-medium">Type:</p>
            <SelectSearchType
              name="type"
              options={[
                'all',
                'manga',
                'novel',
                'lightnovel',
                'oneshot',
                'doujin',
                'manhwa',
                'manhua',
              ]}
            />
          </label>
          <label class="text-neutral-500 text-sm">
            <p class="mb-2 font-medium">Status:</p>
            <SelectSearchType
              name="status"
              options={[
                'all',
                'publishing',
                'complete',
                'hiatus',
                'discontinued',
                'upcoming',
              ]}
            />
          </label>
        </Show>
      </div>
    </form>
  )
}
